version: '3'
#output: prefixed
env:
  SKIP_QUOTA_CHECK: true
  WAF_TEST: false
  CREATE_DIAGRAM: false
  TOOL_KIT_STACKNAME: CDKToolkit
  LASTEST_FIREWALLFACTORY_VERSION:
    sh: curl --silent "https://api.github.com/repos/globaldatanet/aws-firewall-factory/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'
vars:
  prerequisite:
  config: # without .json
  REGION:
    sh: echo $AWS_REGION
  CDK_DEFAULT_ACCOUNT:
    sh: aws sts get-caller-identity |jq -r .
tasks:
  deploy:
    desc: Deploy Stack
    cmds:
      - task: cdkdeploy
      - task: creatediagram
  synth:
    desc: synth Stack
    cmds:
      - cdk synth
    vars:
      ACCOUNT:
        sh: aws sts get-caller-identity |jq -r .Account
      TAGS:
        sh: cat tags/tags.json | jq -j '.[]|"--tags " + (.Key)+"="+(.Value)+" "'
    env:
      PROCESS_PARAMETERS: .config
  diff:
    desc: CDK Diff
    cmds:
      - cdk diff
    silent: true
    interactive: true
    env:
      PROCESS_PARAMETERS: "{{.config}}"
      PREREQUISITE: "{{.prerequisite}}"
  cdkdeploy:
    desc: CDK Deploy
    cmds:
      - cdk deploy --require-approval never {{.TAGS}} --toolkit-stack-name {{.TOOL_KIT_STACKNAME}}
    vars:
      ACCOUNT:
        sh: aws sts get-caller-identity |jq -r .Account
      TAGS:
        sh: cat tags/tags.json | jq -j '.[]|"--tags " + (.Key)+"="+(.Value)+" "'
    env:
      PROCESS_PARAMETERS: "{{.config}}"
      PREREQUISITE: "{{.prerequisite}}"
    silent: true
    interactive: true
  creatediagram:
    desc: Create Diagram
    cmds:
      - if [[ {{.CREATE_DIAGRAM}} = true ]] ; then echo 🤳🏻 $(cfn-dia draw.io -t cdk.out/"$(cat values/{{.config}}.json | jq -r '.General.Prefix')-WAF-$(cat values/{{.config}}.json | jq -r '.WebAcl.Name')-$(cat values/{{.config}}.json | jq -r '.General.Stage')-$(cat values/{{.config}}.json | jq -r '.General.DeployHash')".template.json --output-file $(sed "s/values/diagrams/g;s/.json/.drawio/g" <<< values/{{.config}}.json) --ci-mode --skip-synth); else echo ⏭   Skipping Diagram generation 🤳🏻 ; fi
    silent: true
    env:
      PROCESS_PARAMETERS: values/{{.config}}.json
  testwaf:
    desc: Test of your waf using GoTestWAF
    cmds:
      - echo 🧪  Testing of your new 🔥 WAF using GoTestWAF
      - |
        items=$(cat values/{{.config}}.json | jq -r '.[] | .SecuredDomain[]?')
        for item in ${items[@]}; do
            echo "Using fqdn in 🖥 url : $item"
            ./gotestwaf/gotestwaf --url https://$item --workers 50 --blockConnReset  --wafName="$(cat values/{{.config}}.json | jq -r '.General.Prefix')-$(cat values/{{.config}}.json | jq -r '.WebAcl.Name')-$(cat values/{{.config}}.json | jq -r '.General.Stage')-$(cat values/{{.config}}.json | jq -r '.General.DeployHash')" --configPath=./gotestwaf/config.yaml --testCasesPath=./gotestwaf/testcases --skipWAFBlockCheck --reportPath "./waf-evaluation-report/$(date '+%Y-%m-%d')" --reportName "$(cat values/{{.config}}.json | jq -r '.General.Prefix')-$(cat values/{{.config}}.json | jq -r '.WebAcl.Name')-$(cat values/{{.config}}.json | jq -r '.General.Stage')-$(cat values/{{.config}}.json | jq -r '.General.DeployHash')"
        done
    silent: true
    preconditions:
      - sh: "[ '{{.WAF_TEST}}' != 'true' ]"
        msg: ⏭  Skipping WAF Testing 🧪
  generate-waf-skeleton:
    desc: Generate Skeleton
    silent: true
    cmds:
      - ts-node ./lib/tools/generate-skeleton.ts