Parameters:
  SinkArn:
    Type: String
    Description: The ARN of the sink for the OAM link.
  MonitoringAccountId:
    Type: String
    Description: The AWS Account ID of the monitoring account.
  SourceAccountId:
    Type: String
    Description: The AWS Account ID of the source account.
Resources:
  OAMLink:
    Type: AWS::Oam::Link
    Properties:
      LabelTemplate:
        Ref: SourceAccountId
      ResourceTypes:
        - AWS::CloudWatch::Metric
      SinkIdentifier:
        Ref: SinkArn
    Metadata:
      aws:cdk:path: CloudWatchCrossAccountStack/OAMLink
  CrossAccountRoleFACE29D1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":iam::"
                    - Ref: MonitoringAccountId
                    - :root
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/CloudWatchReadOnlyAccess
      RoleName: CloudWatch-CrossAccountSharingRole
    Metadata:
      aws:cdk:path: CloudWatchCrossAccountStack/CrossAccountRole/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/02KQQ7CIBAA39I7XW01+gCuHgw+wKywTbaUJQFqD4S/m6YXTzOZzAjD9Q6XDrfcW+f7hT9QXwWtV3qSJyYMVCgp3PK7RgygJ3mweMUYoJq40P7tbE0ZynFN9kh/rqM4LhylKYmOYM6n7zjADc7dnJn7tErhQGAO/gABaQRQlAAAAA==
    Metadata:
      aws:cdk:path: CloudWatchCrossAccountStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - il-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

