name: Linting

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - master
      - linting

jobs:
  nodejs-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [20,21]
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint